# scripts/02_tcell_subset.R
library(Seurat)
library(dplyr)
library(ggplot2)
library(plyr) # For mapvalues
# 1. Load Integrated Data
# ==============================================================================
if (!file.exists("results/integrated_obj.rds")) {
  stop("Input file 'results/integrated_obj.rds' not found. Please run script 01 first.")
}
integrated <- readRDS("results/integrated_obj.rds")
# 2. Subset T Cells
# ==============================================================================
# Based on your original code, these global clusters correspond to T/NK lineages
target_clusters <- c("0", "1", "3", "4", "8", "13", "16")
message("Subsetting T cell clusters: ", paste(target_clusters, collapse = ", "))

tcell <- subset(integrated, idents = target_clusters)

# 3. Re-analysis (Re-clustering)
# ==============================================================================
message("Re-processing T cell subset...")

DefaultAssay(tcell) <- "RNA"

# Standard pipeline
tcell <- NormalizeData(tcell, verbose = FALSE)
tcell <- ScaleData(tcell, verbose = FALSE)
tcell <- FindVariableFeatures(tcell, selection.method = "vst", nfeatures = 2000, verbose = FALSE)
tcell <- RunPCA(tcell, npcs = 30, verbose = FALSE)

# Elbow Plot (Optional check)
# ElbowPlot(tcell)

# Clustering at lower resolution as per methodology (res = 0.2)
tcell <- FindNeighbors(tcell, dims = 1:10, verbose = FALSE)
tcell <- FindClusters(tcell, resolution = 0.2, verbose = FALSE)
tcell <- RunUMAP(tcell, dims = 1:10, verbose = FALSE)

# 4. Annotation
# ==============================================================================
# Mapping specific cluster IDs to T cell subtypes.
# Note: These IDs (0, 1, 2...) are generated by FindClusters(res=0.2).
# If your upstream data changes significantly, check these IDs with a DotPlot first.

cluster2celltype <- c(
  "0" = "Naive T",
  "6" = "Naive T",
  "2" = "CD4+ Tcm",
  "7" = "Exhausted T",
  "4" = "Treg",
  "1" = "CD8+ Tem",
  "3" = "CD8+ Tem",
  "5" = "CD8+ Tcm"
)

# Apply annotation
current_ids <- as.character(Idents(tcell))
new_labels <- plyr::mapvalues(
  x = current_ids,
  from = names(cluster2celltype),
  to = cluster2celltype,
  warn_missing = FALSE
)

tcell$celltype <- new_labels
Idents(tcell) <- "celltype"

# Set specific factor levels for consistent plotting order
tcell$celltype <- factor(tcell$celltype, levels = c(
  "Naive T", "CD4+ Tcm", "CD8+ Tcm", "Treg", "CD8+ Tem", "Exhausted T"
))

# 5. Visualization
# ==============================================================================
# Fig 1c: UMAP of T cell subsets
pdf("results/supFig1c_UMAP_Tcells.pdf", width = 8, height = 6)
p1 <- DimPlot(tcell, group.by = "celltype", label = TRUE, label.size = 5) + 
  ggtitle("T Cell Subpopulations")
print(p1)
dev.off()

# Fig 1d: DotPlot of new markers
t_markers <- c("CCR7", "TCF7", "LTB", "IL7R", "CD28", "GZMK", "GZMB", "PDCD1", "HAVCR2")
pdf("results/supFig1d_DotPlot_Tcells.pdf", width = 10, height = 6)
DotPlot(tcell, features = t_markers, group.by = "celltype") + 
  RotatedAxis() + 
  scale_color_gradientn(colours = c("white", "red"))
dev.off()

# Save T cell object
saveRDS(tcell, "results/tcell_subset.rds")
message("Step 02 Complete! Saved to results/tcell_subset.rds")